<?php

namespace FondOfSpryker\Client\UrlStoreStorage\Dependency\Client;


use SprykerShop\Yves\StorageRouter\Dependency\Client\StorageRouterToUrlStorageClientInterface as SprykerStorageRouterToUrlStorageClientInterface;

interface StorageRouterToUrlStorageClientInterface extends SprykerStorageRouterToUrlStorageClientInterface
{
}
